default_install_hook_types: [pre-commit]
default_stages: [commit, push]
default_language_version:
  python: python3.12
ci:
    autofix_commit_msg: |
        ci(pre-commit): Autofixing commit msg from pre-commit.com hooks
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: 'ci(autoupdate): Autoupdating commit msg'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        files: ^backend/
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3.12
        args:
        - --config=api/pyproject.toml
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
        args:
        - --settings-path=api/pyproject.toml
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        additional_dependencies:
        - tomli
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.9.0"
    hooks:
    -   id: mypy
        args:
        - --config-file=api/pyproject.toml